### ISSUE TITLE
"Don't show" option in the form

### ISSUE THREAD

**Issue by antekpiechnik** [stillmaintained/stillmaintained#12]
I have a few projects which I used with github to simply share the code with fellow students or simply for my own purposes and I am not sure I want them displayed on stillmaintained. How about a fourth options stating that it shouldn't show up there at all ?

**Comment by jeffkreeftmeijer** [comment]
c42c47bf032ec9f61ed095532a93636c4add0869

Thanks Antek, great idea. :)
