### ISSUE TITLE
Support forks

### ISSUE THREAD

**Issue by garybernhardt** [stillmaintained/stillmaintained#13]

**Comment by jeffkreeftmeijer** [comment]
The reason I didn't implement it in the first place was to avoid the confusion about which one's the original repository. Also, I didn't think people would actually want to put up their forks, since they're mostly made to patch the main repository.

Any ideas on how to do a nice implementation? :)

**Comment by jeffkreeftmeijer** [comment]
Add fork support, closed by ad30da98f32fb14dc9d74f4f88a3a08662642cb7
