### ISSUE TITLE
Forked repositories

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [stillmaintained/stillmaintained#18]
You can add forked repositories now and they'll get a proper status page, but they won't show up in the project list right now. I know this is not ideal at all, but I'm not sure how to properly solve this without cluttering the lists with forked repositories.

An idea would be to add a button to the lists to show forked repositories. Any other ideas?

**Comment by rkh** [comment]
when setting the project status, add a check box like "include this in project listing" or something. would love to have that in general (maybe just make the default dependent on whether it is a fork or not).

**Comment by jeffkreeftmeijer** [comment]
When adding your projects, the projects are set to "Don't list this project" by default and the projects only get listed when you give it a status. I'm not sure how much it would help to move this to a separate checkbox.

I'll keep that in mind though. :)

**Comment by rkh** [comment]
Yeah, you're probably right. Maybe just add it for forks. Or maybe add the fork to the projects lists if the status for the projects it's forked from is not set. Maybe that's a bit complex, though. In regard to caching and what not.

**Comment by jeffkreeftmeijer** [comment]
Forked projects show up on user/organization specific project lists now: http://stillmaintained.com/sinatra , marked with "(fork)".

**Comment by rkh** [comment]
Awesome!
