### ISSUE TITLE
List the projects and radio buttons in a table on the "Adding your work" page

### ISSUE THREAD

**Issue by nvie** [stillmaintained/stillmaintained#19]
I think this might make the page a bit more compact if you have many projects. You could have a row per project and columns for the options. This would take a bit less scrolling when entering your input.

WDYT?

**Comment by jeffkreeftmeijer** [comment]
Sounds like a nice idea, but I'm not sure if I want to make the pages any wider. I agree the form needs some work, though. :)

**Comment by inkel** [comment]
At first I agreed with the idea of a table or similar layout for the projects, but then I realized that if for instance you have many projects then the table header might disappear or be far away from the current option, which I think it's more error prone than the current layout, which even though it repeats itself and produces longer forms it is very project specific.
