### ISSUE TITLE
iPhone / iPad viewport meta tag

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [stillmaintained/stillmaintained#2]

**Comment by inkel** [comment]
I'm working on a [related feature](https://github.com/inkel/stillmaintained/tree/feature/responsive), that is, adding responsive web design to the application. It still needs some tweaks and fixes but is a start.

**Comment by jeffkreeftmeijer** [comment]
@ivanasetiawan: @inkel told me we might need the logo in different sizes for this. Can you add psd of the header in a directory called "resources" in the project root so we can work with it?  :)

**Comment by ivanasetiawan** [comment]
sure :)

**Comment by inkel** [comment]
@ivanasetiawan by any chance do you have a standalone PSD version of the logo? In order to be able to resize it.

@pyrotechnick requests a nice _feature_ in issue #11: having a persistent banner on top of the pages with a link to the home page. I was planning to put the logo and the site H1 for this banner (if you both agree that is a good idea, of course), so I'll probably send you later a mock up. Is that ok with you?

**Comment by jeffkreeftmeijer** [comment]
@inkel of course, I'd love to see a mockup!

Can't you use the PSD @ivanasetiawan sent? The logo is in there, right? :)

**Comment by inkel** [comment]
Yeah, I eventually found the logo. I'm not very good with graphic tools :)

**Comment by inkel** [comment]
It's official: I suck at graphical skills. Anyway, I continued working on responsive web design for the application, you can see some screenshots at [my Flickr set](http://www.flickr.com/photos/inkel/sets/72157626613570503).

If you have a Flickr account feel free to leave any comment you like, I will push the branch later.

**Comment by jeffkreeftmeijer** [comment]
It's looking awesome. Please let me know when it's done so I can merge it in. :)

**Comment by inkel** [comment]
I'm glad you like it!

I think it's almost done, at least the responsive part. There are some other improvements that I think would add better usability to the site, but those are outside the scope of _this_ issue ;)

**Comment by inkel** [comment]
Well, at least for iPhone and iPad I think I'm done ;)

I don't have an iPad so I wasn't able to really test it. On my iPhone 3GS looks, modestly speaking, great. Tomorrow at the office I'll ask a coworker of mine for his iPad and test it for real. In the meantime if you have an iPad, feedback is appreciated!

Everything is pushed at the feature/responsive branch, however I think I made a mistake and also pushed a wrong commit @ff0f3c5, sorry about that, I still need to improve my git skills :S

**Comment by jeffkreeftmeijer** [comment]
I reverted @ff0f3c5 and I'll check the responsive branch in the iPhone and merge it in. Awesome work! :)

**Comment by inkel** [comment]
Thanks! I am looking forward to your feedback/approval :)

**Comment by ivanasetiawan** [comment]
@inkel cool stuff :)

**Comment by inkel** [comment]
Thank you Ivana!

**Comment by jeffkreeftmeijer** [comment]
Looking awesome. The only thing I'm having trouble with is the ad (and the webbynode logo). Unless anyone has a better idea, let's just hide it (using display:none for now). Can you pick that up @inkel? If you can't, I'd be glad to do it, but I won't be able to until monday. Thanks for your amazing work (you too, @ivanasetiawan)! :)

**Comment by inkel** [comment]
I sure can! I had some problems with that too, I came up with the best solution I've found at that moment, because I didn't want to modify too much the HTML.

One of the things that I had in mind was changing the HTML in some places. My idea is not fully changing the layout at all, I think it's great now, but probably some elements could be coupled together or better reorganized in a way that would make more easy to position things like the ad and webbynode logo, or also the persistent banner proposed in #11 (which I think it's a very good idea). In a couple of minutes I'll push the display:none fix.

**Comment by inkel** [comment]
@96e47657a859ec242c4b hides the ad and webbynode logo for resolutions lower than 1024px.

**Comment by jeffkreeftmeijer** [comment]
Thanks! You're fast! 

The iPad version is great, but the iPhone version doesn't have a logo now (I'm not sure if that's a decision you made or something that went wrong, please enlighten me) and the content gets pushed to the sides a bit when holding the device horizontally, maybe we can add a little margin there?  Here's a screenshot of what I mean: http://skitch.com/jkreeftmeijer/fyafy/screen-shot-2011-05-22-at-11.55.01-am :)

Again, awesome work! About changing the HTML: I really like Ivana's design, but if you need to change any markup to make it more awesome, please do. :)

**Comment by inkel** [comment]
Yes, the iPhone version excluded the logo. I was unable to make it smaller and look good, and there were not too much room for it, so for the moment it's hidden.

Regarding the padding on the iPad when holding it horizontally no problem, I'll add a bit of padding.

Last but not least: I do not pretend to change Ivana's design, I really like it too, what I meant was only changing the structure, not the outcome.

**Comment by jeffkreeftmeijer** [comment]
Can't we css-resize the logo for now? 

The padding was fine on the iPad, it's the iPhone version I was talking about.

I wasn't talking about changing Ivana's design at all, I was talking about the structure. Improvements are always welcome! :)

**Comment by inkel** [comment]
Logo and padding fixed, committed and pushed! Commits @8da0b892901905d3afed and @12bf39123a003c769d01.

As for changing the structure, I'll make a new branch for that, so this is ready for merging if you like to :)

**Comment by jeffkreeftmeijer** [comment]
I checked the iPhone and iPad versions and they look awesome. I've merged feature/responsive into develop and released 0.1.1. Thanks! :D

**Comment by inkel** [comment]
I'm glad you like it!

I really enjoyed contributing, I'll do my best to keep doing it. Thanks to you for the opportunity!
