### ISSUE TITLE
Not quite abandoned, not quite still maintained

### ISSUE THREAD

**Issue by mcmire** [stillmaintained/stillmaintained#20]
Hi there! First off, thanks for Still Maintained, I like the idea. One feature request I have is for a another status. Right now we have essentially "still maintained", "willing to give to someone else", and "not looking and abandoned". I think "still maintained" could be interpreted as "actively working on or maintained". However I have several projects which I haven't worked on for a while, but which I think are still a good idea and if anyone came along and asked me for a feature request or something I would be happy to resume working on it. So for these projects technically I am still maintaining them, just not right now. So I wonder if we need a middle status, perhaps "stale" or "not actively worked on" or something like that. What do you think?

**Comment by jeffkreeftmeijer** [comment]
I'd like a on-hold state for people still willing to maintain projects but not actively working on them right now. I'm not sure about the name though... Thoughts? Anyone? :)

**Comment by joshk** [comment]
In a nutshell I like the idea of another status, finding the write word / phrase is the hard part. Caution also needs to be taken as when do you draw the line on adding new statuses? 

In general I support this, but it all comes down to the word / phrase, brainstorm time me thinks!

**Comment by afeld** [comment]
I think "still maintained" still applies here - if it doesn't need maintenance, then not making any changes shouldn't count against you!

**Comment by inkel** [comment]
As I've commented in #7 I think that a _looking for contributors/help_ might be an interesting state for a project. Sometimes you're interested in making your project grow or you think the idea is good but some things are missing (e.g. documentation, bug fixing, etc.) and you don't have the time to work on them but are willing to accept patches/pull requests.

**Comment by mcmire** [comment]
I like that. I think that's closer to what I was trying to say.

**Comment by trans** [comment]
+1 for "looking for help"

I'll also mention that a <i>bounties feature</i> could be pretty helpful. In fact, GitHub could do something like CrowdSpring and make a small percentage off completed bounties.
