### ISSUE TITLE
Organizations

### ISSUE THREAD

**Issue by trans** [stillmaintained/stillmaintained#25]
How to handle organizations? I can't find a way to  do it.

**Comment by doriath** [comment]
Right now there is partial support for organizations, but I would like to rewrite that functionality. I would like to add following features:
- separate user repositories and organization repositories. First, all user repositories will be listed, then the organization name will be displayed (e.g. 'Projects of <org name> organization') and then the list of projects of that organization. That way user can see if project belongs to organization or to him. (when user forks project from organization, we get two projects with the same name and we need to distinguish them).
- allow to edit organization project only when we have admin privilages to that project.

What do you think @jadb? Is it enough to handle organizations for stillmaintained?

**Comment by jadb** [comment]
Sounds perfect @doriath!

**Comment by doriath** [comment]
Sorry it took me so long but I finally reimplemented the organization logic in stillmaintained and it should work as described in my previous post.

I believe we can close this issue now.

**Comment by jadb** [comment]
Very nice work you got done there. Thanks!
