### ISSUE TITLE
Need a way to link in "Organizations"

### ISSUE THREAD

**Issue by blister** [stillmaintained/stillmaintained#3]
Maybe I'm missing something, but I am the "owner" of a GitHub organization that handles all of my actual open source projects. Everything that is listed as a project under my account is silly little stuff that I hack on from time to time while all of the big "projects" are listed under the Organization.

When I linked my account to stillmaintained, it didn't give me the option of doing anything with my Organization's projects. 

Thoughts?

**Comment by jeffkreeftmeijer** [comment]
Hi Eric,

You're absolutely right. Right now, stillmaintained only fetches the user's repositories. Adding organization support is high on the list, but it's a separate API: http://support.github.com/discussions/api/133-beta-organization-api

Thanks for creating this issue so I don't forget. :)
- Jeff

**Comment by jeffkreeftmeijer** [comment]
Closed by 05e58dfb06d457b20ae02d76efc2d5861831a7ec

**Comment by jeffkreeftmeijer** [comment]
Closed by 05e58dfb06d457b20ae02d76efc2d5861831a7ec
