### ISSUE TITLE
Branches role

### ISSUE THREAD

**Issue by doriath** [stillmaintained/stillmaintained#31]
Hey @jeffkreeftmeijer and @jadb,

I would like to ask about the branches `develop` and `master`. I see that `develop` is the base branch instead of `master`. What is the reason for that?

How the development of new features have been done so far? You have been adding them to `develop` branch, and then when you wanted to deploy, you merged it with `master` branch?

I was a little confused yestarday, when I started to change the project.

Thanks,
Tomasz

**Comment by jeffkreeftmeijer** [comment]
Hey Tomasz,

I hope [this article](http://jeffkreeftmeijer.com/2010/why-arent-you-using-git-flow/) answers your question. Feel free to figure your own branching strategy with @jadb, though. :)

-- Jeff

**Comment by doriath** [comment]
Hey @jeffkreeftmeijer,

Thanks for the article. I will try to follow your branching strategy.

-- Tomasz
