### ISSUE TITLE
No more inbox on GitHub

### ISSUE THREAD

**Issue by doriath** [stillmaintained/stillmaintained#32]
Github removed the inbox feature, that stillmaintained was using. We could fix it, by memorizing the email address of every user, and show the email link instead of github inbox link. This link appears in `views/not_found.haml` and `views/projects/show/searching.haml`.

Also, I suggest removing the last line in README, that point to jeff's github inbox (that does not exist any more).

What do you think @jadb?

**Comment by jadb** [comment]
@doriath, sure why not. Better than having broken links.

**Comment by doriath** [comment]
Unfortunatelly, not every user has a public email, so I decided to replace the links to github profile page instead. Using email address, would require one additional call to github api and also we would need to handle users without emails somehow. This solution should be enough for now, to fix broken links.

https://github.com/stillmaintained/stillmaintained/commit/50229229d3a42cd06e2e6b07c5e4b6266ec1031f
