### ISSUE TITLE
Not existing repositories

### ISSUE THREAD

**Issue by doriath** [stillmaintained/stillmaintained#33]
There are times when github project is abandoned and then removed from it. I would like to discuss how stillmaintained should react on following situation:

The user creates a project and logins to the stillmaintained website. That automatically creates the project on stillmaintained website. Later, the project is removed from the github and user logins again to stillmaintained website. What should we do with that removed project?

Right now, such project will be displayed on the list of user's projects and it is impossible to remove it from there (the list of projects is only growing for every user).

In my opinion, such projects should be removed from the stillmaintained website (not just hidden or marked as such). What do you think @jadb? Is there any reason why we would like to keep them?

**Comment by jadb** [comment]
@doriath - I totally agree. If there is no page for the project to be found on GH, there shouldn't be one on SM either. How do you plan on checking those against GH?

**Comment by doriath** [comment]
I am planning to implement following feature. Right now, every time user signins, we are fetching all his repositories from github. Base on that information we are updating and creating new projects. I want to add the function, that will check for projects that exists on StiiMaintained but do not in github (just by comparing the list from github and stillmaintained) and remove them. It should not be so hard to implement as we have all the information already.

In this feature, the check will only happens when user signins. This will not include periodical checks, manual checks from command line, etc. (I would like to discuss it as separate feature).

**Comment by jadb** [comment]
It could work but I think shell + cronjob would be more appropriate for such task. No?

It is easier to then call that same shell when the user signs in.

**Comment by doriath** [comment]
I can make it work as cronjob too. 

How often do you think we should check all users and remove theirs not existing projects? What do you think about checking users every week?

**Comment by doriath** [comment]
It took me some time to implement this, but it should be working now. Every time user sign in, we remove not existing repository, and also we do this automatically every week (with cronjob executing rake task).

**Comment by jadb** [comment]
yay! nice! haven't checked it yet but will do shortly.
