### ISSUE TITLE
Project is missing

### ISSUE THREAD

**Issue by AlekSi** [stillmaintained/stillmaintained#34]
My page on http://stillmaintained.com says: "Hi AlekSi, here's a list of every Github project you started." But there at least one project is missing: https://github.com/AlekSi/nut

**Comment by doriath** [comment]
Hi, thank you for reporting the bug.

I found the cause and here is short explanation. Github API is using pagination and returns only 30 responses (I didn't know about it before). If you go to https://api.github.com/users/AlekSi/repos, you will not see the nut project. In the headers, github returns links to the next page that we should use:

```
Link: <https://api.github.com/users/AlekSi/repos?page=2>; rel="next", <https://api.github.com/users/AlekSi/repos?page=3>; rel="last"
```

I will try to fix that as soon as possible.

**Comment by doriath** [comment]
Could you check if it is working now? I don't have so many repos to check if pagination is working correctly.

**Comment by AlekSi** [comment]
I don't see any changes.

**Comment by doriath** [comment]
Sorry, I found out that I fixed the problem but did not deployed the new version. It is working right now. Once you confirm it, I will close that issue.

**Comment by AlekSi** [comment]
Yes, it works. Thank you.
