### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by hkjels** [stillmaintained/stillmaintained#37]
How do you add an interactive banner? Adding a static resource of "still maintained" kind of defeats the purpose as I would have to maintain the banner in my readme manually.

**Comment by hkjels** [comment]
Adding some useful bits about the subject to the wiki would suffice I guess.

**Comment by doriath** [comment]
In theory, the stillmaintained README contains the dynamic banner/badge so you can check how it can be done. But I agree, there is no documentation about how to add the badge to the README file. I will write the wiki subject and point to it from the README file. Thanks for reporting it!

**Comment by jadb** [comment]
Here's a shameless adaptation of Travis-CI's how-to for StillMaintained: 

https://github.com/stillmaintained/stillmaintained/wiki/Adding-status-image-to-README-file
