### ISSUE TITLE
Project descriptions need to be HTML escaped

### ISSUE THREAD

**Issue by joshgoebel** [stillmaintained/stillmaintained#38]
Reference:

https://github.com/stillmaintained/stillmaintained/commit/9ba9020d3db4d41176204b0ca5e63e012c39e7b8#commitcomment-3004919

**Comment by doriath** [comment]
Commit 5025faf4c4676d7679a86681d995310a82cd3ba8 fixes the bug. Thank you for reporting it!

**Comment by joshgoebel** [comment]
Thanks. I knew it'd be easy.
