### ISSUE TITLE
Down

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [stillmaintained/stillmaintained#39]
I've been getting reports via Twitter that StillMaintained is down (http://www.downforeveryoneorjustme.com/stillmaintained.com). @jadb, could you check it out?

**Comment by jadb** [comment]
Hey Jeff,

I have been struggling with RackSpace - was out of the country and the credit card was maxed out. They wouldn't wait for me to get back before suspending the account. I am now trying to get them to re-instate my access so I can re-activate the server.

Waiting for them to get back to me. I will keep you posted.

:(

**Comment by jadb** [comment]
Ok,

Gained access back and everything should be back online within the next 10 to 20 mins according to them.

I will check and update/close this issue then.

**Comment by jadb** [comment]
Site is back up. Sorry for the downtime.

**Comment by doriath** [comment]
Thanks!
