### ISSUE TITLE
Performance concern: Badges not loading

### ISSUE THREAD

**Issue by patcon** [stillmaintained/stillmaintained#40]
Hi there,

Really like the idea of the project, but since it's such a "nice to have", then I'm sure people are going to be reluctant to use it if the functionality of its targeted feature set fails into question. Currently, the site itself is very slow to log into, and the generation of the (presumably cached) badges is taking forever.

I don't think I'll end up using the service in light of this, but just thought I'd let you know the rationale for passing. It might be worth throwing more resources at the project if you're interested in its long-term success.

Again, thanks very much for what you've created! :)

Ref: https://stillmaintained.com/proviso/proviso.png

**Comment by patcon** [comment]
Ah... seems it was an https issue in the recommended template :) You might want to disable https all-around on the site. It's incredibly slow.

**Comment by doriath** [comment]
Hi,

Thanks a lot for reporting the problem. I fixed the wiki, to point to http instead of https (I believe https is not working at all). Is the page working slowly on http too, or only https was a problem?

**Comment by patcon** [comment]
Thanks! It was just https :)
