### ISSUE TITLE
do an autocomplete search of repositories instead of creating radio buttons for every single repository

### ISSUE THREAD

**Issue by jonathanong** [stillmaintained/stillmaintained#46]
terrible UI. should be:
1. search for repo
2. select maintenance option
3. log the change or something
4. clear the search menu for a new search

**Comment by jadb** [comment]
For now, we have no plans of adding functionality to the application. I have labeled it as an 'future-enh'  and closed it. When, and if, we decide to work on the codebase (aside from fixing critical bugs), it will be taken into consideration.

Thanks for your input @jonathanong.
