### ISSUE TITLE
Add links to badges on site

### ISSUE THREAD

**Issue by h4cc** [stillmaintained/stillmaintained#48]
I cant find the links for badges on your site.
Please add them somewhere, so its easier to use them.
(This will also spread usage of your site)

**Comment by h4cc** [comment]
Ping pong?

**Comment by jadb** [comment]
Hey h4cc,

Sorry for the late reply. I am actually working on v2 and new badges + instructions are top priority. 

Will update this issue when I am deploy the related changes.

**Comment by moleksyuk** [comment]
HI @jadb 
svg files are not supported by github anymore - http://stackoverflow.com/questions/13808020/include-an-svg-hosted-on-github-in-markdown

Any plans to migrate to png?

**Comment by jadb** [comment]
Thanks @moleksyuk! It's fixed now.
