### ISSUE TITLE
Can't change the status of repos on stillmaintained.com

### ISSUE THREAD

**Issue by brycefisher** [stillmaintained/stillmaintained#49]
I just logged in to checkout this project and mislabeled some of my repos. I feel a bit silly here, since I can't figure out how to change my repos status -- I'm sure I'm missing something really obvious! Sorry to be that guy :-)

**Comment by doriath** [comment]
I think you have to repeat the same steps:
- go to http://stillmaintained.com/
- click "Log in via Github to add your work"
- perform any edits for your projects
- click "Submit"

**Comment by brycefisher** [comment]
Awesome! Thanks
