### ISSUE TITLE
Provide a simple API that returns icons

### ISSUE THREAD

**Issue by nvie** [stillmaintained/stillmaintained#5]
It would be cool if there were a simple API call that returns a small PNG icon of the project's status. Let's say at:

```
https://stillmaintained.com/api/v1/status/foo/bar
```

So one could reference them in an image, like so: `<img src="https://stillmaintained.com/api/v1/status/foo/bar" />`.

Even the grand masters of Github themselves could then show the project's status right on the project page by simply including a small HTML snippet (if they like the idea).

The initial version could use PNG's of the tiny icons that currently show on stillmaintained.com. Otherwise, someone must create nicer looking icons.

**Comment by jeffkreeftmeijer** [comment]
Great idea. I would probably go for `http://stillmaintained.com/jeffkreeftmeijer/fuubar.png` as the url though, just to keep it simple.

What icons should be used? Currently, StillMaintained doesn't really use _any_ images (except for the fork me ribbon). I think you're talking about the colored bullets on the project list?

Can somebody create nice icons? :)

**Comment by nvie** [comment]
Yeah, that URL would be simpler, thus nicer. Keep in mind though that if you'd really like to propose this as a feature on Github itself (as far as those requests would be taken seriously), that you'd need an HTTPS URL for that.

**Comment by jeffkreeftmeijer** [comment]
Robert added this in aa06e1a5fdf7f3f95968854f7091c3fac39fab3d, but I'm not sure about the icons, since they're just colored bullets.

Can we make a button that has the little colored bullet and a text next to it saying "Still maintained" / "Looking for a new maintainer" / "Abandoned"?

Any other ideas? :)

**Comment by matsimitsu** [comment]
Yeah i just created 'bigger' dots in photoshop :)

Text might be to large, but we could also just make a few variations, the code is already there.

**Comment by jeffkreeftmeijer** [comment]
Closed by 4d81bde4e534acf5214488d36506922146415873 :)
