### ISSUE TITLE
Frontend

### ISSUE THREAD

**Issue by ivanasetiawan** [stillmaintained/stillmaintained#56]
Hi! I'd like to help with frontend/UX design if needed?
Who should I be contacting? :)

Thanks!

**Comment by jadb** [comment]
Hey! Great to hear. I'd be the person and as you can see, not a design type of person! Let me know if you prefer here, over IRC or on Skype.

**Comment by ivanasetiawan** [comment]
Skype please :) My ID is ivanasetiawan. Looking forward!

**Comment by jadb** [comment]
@ivanasetiawan just added you, sorry been really busy. Looking forward too!
