### ISSUE TITLE
Broken badges

### ISSUE THREAD

**Issue by hellopablo** [stillmaintained/stillmaintained#57]
Hi,

I'm finding all the badges on my projects are broken. I only just joined and set it up, but I don't think it's an issue on my part.

The direct URLs work just fine, it's when they're cached behind githubusercontent that they 404.

Not sure if it's something you can address with cache headers etc?

Cheers!

Pablo.

**Comment by ZeeCoder** [comment]
I had a similar issue.
The markdown code provided on the site doesn't work with https, I had to replace them with http.

**Edit:** Ugh, I just realised even this repo's badge is broken. O.o

**Comment by CzBiX** [comment]
@jadb Just as @ZeeCoder said, HTTPS of this site have some issue.
It only provided one SSL cert without the full cert chain, please fix it.

**Comment by michaelbutler** [comment]
It looks like the `stillmaintained.com` domain has been expired and bought up by a domain squatter and is currently asking about $1600 USD for it.
