### ISSUE TITLE
Is stillmaintained still maintained?

### ISSUE THREAD

**Issue by davisonio** [stillmaintained/stillmaintained#59]
stillmaintained.com seems to have expired...

/cc @jeffkreeftmeijer

**Comment by jeffkreeftmeijer** [comment]
@jadb has been maintaining the project for the last couple of years. What's up Jad? :)

**Comment by dgoguerra** [comment]
Yes, the links to badges it provides for projects README's are broken. The irony...

**Comment by davisonio** [comment]
The domain gets deleted 30 days after expiration date (December 28) I believe, so we don't have long. I wouldn't like for this great project to die... @jadb

**Comment by acrogenesis** [comment]
pinging also @doriath

**Comment by davisonio** [comment]
Looks like the domain is now on backorder and [bidding has started](http://www.namejet.com/Pages/Auctions/BackorderDetails.aspx?domainname=stillmaintained.com)... Currently at $69.

**Comment by jadb** [comment]
Arg! What?! Very long story...

I am in contact with BuyDomains.com who are auctioning it to try and deal a buy it now price (they initially asked for 5K). 

Once all this is (hopefully) resolved, I'll get time to write more on the WTF.

**Comment by Potherca** [comment]
Everything linking to http://stillmaintained.com/ is already broken as-is. Why not just use a different domain (like `.center`, `.directory`, `.help` or `.software` or something less exotic like `.net`) and tell BuyDomains to stuff it?

**Comment by jadb** [comment]
I have thought of this but then I found out about this https://github.com/badges/shields/issues/607 and in its current state, SM doesn't do much more than having the user update it (doesn't automatically tell if stale). Which makes a badge on shields acts the same with the only difference that there is no UI to manage the status of ones' collection of projects.

I had plans to automate some stuff by making it work with issuestats.com to get a feeling of a repository's _heartbeat_ and that would pump so new life into the project but been so short on time :disappointed:  

Anyone cares to help?

**Comment by Potherca** [comment]
I'm afraid I don't really have any time to contribute :disappointed:. Anyone else?

**Comment by maxlinc** [comment]
Is the data lost or just the domain?

**Comment by jadb** [comment]
Just the domain.

**Comment by davisonio** [comment]
What do we think it the next step here? I don't think there's any point in going through the BuyDomains route - they're incredibly expensive.

As for myself contributing, I may possibly be able to help in a few ways here and there.

A few ways forward:
- someone splash out the cash from BuyDomains
- use a new domain e.g. still-maintained.com, stillmaintained.net
  - perhaps write a GitHub bot to help fix the broken links
- change (domain) name of project + also a new direction and roadmap for the project

Let's not forget another two projects that exist http://isitmaintained.com and http://unmaintained.tech that are also similar.

**Comment by rnhurt** [comment]
It might be helpful to get a dump of the data.  Maybe we can get a Jekyll page up and running and use pull requests to update the status of the applications.

**Comment by Kristinita** [comment]
@doriath, @jadb, status?

Thanks.
