### ISSUE TITLE
Adoption Bounties

### ISSUE THREAD

**Issue by trans** [stillmaintained/stillmaintained#7]
It would be very cool if their were a way to have adoption bounties. So that anyone who would like to see a project continued that has been abandoned or up for adoption can contribute to the fund. Perhaps it can be built on GitHub's Pledgie plugin.

**Comment by inkel** [comment]
According to GitHub they've discontinued the Pledgie plugin (see the update in the original post [Getting Paid the Open Source Way(https://github.com/blog/57-getting-paid-the-open-source-way).)

One thing I was thinking lately was adding a new state other than the existing ones for projects that are not abandoned nor active nor looking for a new maintainer but looking for collaborators. Then you can search for projects that are looking for help (for instance fixing bugs or writing documentation). I don't know if it's a good idea or this the place to ask for help, but it might work.

**Comment by jeffkreeftmeijer** [comment]
Let's discuss this in #20. I'll close this one for now. :)
